# Generated by Django 5.2.5 on 2025-12-10 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileYoutube',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('gpm_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('raw_proxy', models.TextField(blank=True, null=True)),
                ('profile_path', models.CharField(max_length=255)),
                ('browser_type', models.CharField(max_length=255)),
                ('browser_version', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Profile Youtube',
                'verbose_name_plural': 'Profiles Youtube',
            },
        ),
        migrations.CreateModel(
            name='PlaylistYoutube',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('name', models.CharField(max_length=255)),
                ('youtube_link', models.CharField(max_length=10000)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.profileyoutube')),
            ],
            options={
                'verbose_name': 'Playlist Youtube',
                'verbose_name_plural': 'Playlists Youtube',
            },
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('youtube_link', models.CharField(max_length=10000)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.playlistyoutube')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Video Youtube',
                'verbose_name_plural': 'Videos Youtube',
            },
        ),
    ]
