# Generated by Django 5.2.5 on 2025-12-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard Proxy',
                'verbose_name_plural': 'Dashboards Proxy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('youtube.profileyoutube',),
        ),
        migrations.CreateModel(
            name='ImportToolProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Import Tool Proxy',
                'verbose_name_plural': 'Import Tools Proxy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('youtube.profileyoutube',),
        ),
    ]
