# Generated by Django 5.2.5 on 2025-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_dashboardproxy_importtoolproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardproxy',
            options={'verbose_name': 'ToolsDashboard', 'verbose_name_plural': 'Tools Dashboards'},
        ),
        migrations.AddField(
            model_name='playlistyoutube',
            name='number_of_videos',
            field=models.IntegerField(default=0),
        ),
    ]
